<string>:0:0:WARNING:IO:IO_LOAD_ERROR: failed to load external entity "file:/C:/Users/agilb/Documents/GitHub/DiscreteMathForComputing/source/ex_projectII-ch.ptx"
file:/C:/Users/agilb/Documents/GitHub/DiscreteMathForComputing/source/main.ptx:26:0:ERROR:XINCLUDE:XINCLUDE_NO_FALLBACK: could not load file:/C:/Users/agilb/Documents/GitHub/DiscreteMathForComputing/source/ex_projectII-ch.ptx, and no fallback was found
<string>:0:0:WARNING:IO:IO_LOAD_ERROR: failed to load external entity "file:/C:/Users/agilb/Documents/GitHub/DiscreteMathForComputing/source/ex_projectIII-ch.ptx"
file:/C:/Users/agilb/Documents/GitHub/DiscreteMathForComputing/source/main.ptx:26:0:ERROR:XINCLUDE:XINCLUDE_NO_FALLBACK: could not load file:/C:/Users/agilb/Documents/GitHub/DiscreteMathForComputing/source/ex_projectIII-ch.ptx, and no fallback was found